services:
  partners.repository.widget:
    class: Backend\Modules\Partners\Domain\Widget\WidgetRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - Backend\Modules\Partners\Domain\Widget\Widget

  partners.handler.create_widget:
    class: Backend\Modules\Partners\Domain\Widget\Command\CreateWidgetHandler
    arguments:
      - "@partners.repository.widget"
    tags:
      - { name: command_handler, handles: Backend\Modules\Partners\Domain\Widget\Command\CreateWidget}

  partners.handler.update_widget:
    class: Backend\Modules\Partners\Domain\Widget\Command\UpdateWidgetHandler
    tags:
      - { name: command_handler, handles: Backend\Modules\Partners\Domain\Widget\Command\UpdateWidget }

  partners.handler.delete_widget:
    class: Backend\Modules\Partners\Domain\Widget\Command\DeleteWidgetHandler
    arguments:
      - "@partners.repository.widget"
    tags:
      - { name: command_handler, handles: Backend\Modules\Partners\Domain\Widget\Command\DeleteWidget }
  partners.widget.form_type:
    class: Backend\Modules\Partners\Domain\Widget\WidgetType
    arguments:
      - "@fork.settings"
    tags:
        - { name:form.type }
